### PR TITLE
Fix issue when path sets as icon for listitem object

### PR DESCRIPTION
**Pull request by vkravets**
This change is [Reviewable](https://reviewable.io/reviews/sinap/kodiswift/9)

### CODE REVIEW

**Comment by vkravets** [comment]
I've noticed that at [kodiswift/xbmcmixin.py:312](https://github.com/Sinap/kodiswift/blob/master/kodiswift/xbmcmixin.py#L312) used `item.set_played(True)`([kodiswift/xbmcmixin.py:345](https://github.com/Sinap/kodiswift/blob/master/kodiswift/xbmcmixin.py#L345)) is it right? Should we change it to `item.playable = True`  I think it much right way to have consistent state of ListItem version xbmc.ListItem

@Sinap What you think?

**Comment by afrase** [comment]
@vkravets You are correct. I must have missed that one when refactoring. The old `xbmcswift2/listitem.py` copied the methods from `xbmcgui.ListItem`. I want to kodiswift's API to be more pythonic so I converted the methods into properties and removed the `set` and `get` prefixes.

**Comment by vkravets** [comment]
@Sinap ok in this case I will update test now, but it will be failed due to bug of played/playable behavior

**Comment by vkravets** [comment]
Closed this to open new one based on develop branch

**Comment by vkravets** [comment]
#14 was created

**Pull request closed without merging**
